### ISSUE TITLE
Guilds are Really Buggy and seems to be seen me as just a member 

### ISSUE THREAD

**Issue by 8BitCR** [FightRPG-DiscordBotRPG/FightRPG---Discord---BugTracker#1]
**Describe your issue.**  

When trying to use the guild functions it constantly says im not the guild master and doesn't let me use the different commands as the leader 

**Copy and Paste the error here**

```js

< err.psuh is not a function
at (/home/admin/Discord-Bot-RPG-Server/bin/Guild.js:352:17 >

```

** Give a screenshot for more precise context **

![screen shot 2018-12-16 at 11 06 26 am](https://user-images.githubusercontent.com/45920433/50056510-c9f05f00-0122-11e9-8ffd-42e1a3437544.png)

**Comment by Roncarlos** [comment]
The err.psuh was a typo error.
Nethertheless i found several bugs related to checking if member exist and checking your rank.
It should be fixed now.
